### ISSUE TITLE
OEP8: Broken example link

### ISSUE THREAD

**Issue by nickfujita** [ontio/OEPs#32]
The link to the reference implementation seems to be broken. Is there an updated reference implementation link?

**Comment by javajoker** [comment]
Good idea! let's do it

**Comment by jonatanblockchain** [comment]
Yes, submodule can be nice.

@javajoker @Honglei-Cong Changing the subject, in relation to "dApp Incentive Model" What do you think create a new repository called for example github.com/ontio-dapps with a complete example of different topics like game/dex/mobile covering cyano+frontend+smartcontract+backend .Developers can learn by example.
