### ISSUE TITLE
OEP code should be in Python

### ISSUE THREAD

**Issue by WyattMufson** [ontio/OEPs#45]
Currently the functions examples are written in C# (see OEP4, OEP5, etc). Since Python is the recommended language for use, these examples should be offered in Python instead.

**Comment by Honglei-Cong** [comment]
Template codes in python is available at https://dev-docs.ont.io/#/docs-en/smartcontract/02-template

**Comment by WyattMufson** [comment]
Awesome, good resource to have.

I meant more the C# description for `transfer`
```
public static bool transfer(byte[] from, byte[] to, BigInteger amount)
``` 
Should it be written in Python like this?
```
def transfer(from, to, amount)
```

**Comment by WyattMufson** [comment]
@Honglei-Cong opened a PR to resolve this
