### ISSUE TITLE
OEP5 Improvements

### ISSUE THREAD

**Issue by WyattMufson** [ontio/OEPs#46]
I have three issues with the current OEP5:

1) What is the point of the `takeOwnership` method? I don't think it is needed and it should be merged with `transfer`. Both methods take two arguments, `toAcct` and `tokenID`. `transfer` checks to see if the caller is the token owner while `takeOwnership` checks to see if it is either the token owner or an account which has been approved.

I think `transfer` should have the same behavior as `takeOwnership` and then `takeOwnership` should be removed from the OEP.

2) I additionally think that there should be a method to list all of the tokens owned by a certain wallet. With the current OEP there is no way for a user to query their tokens. I think there should be a separate `getTokens` method, or that `balanceOf` should return an array of tokens instead of the amount of tokens. This will make OEP5 assets more usable.

3) There is currently no mention of preventing cross-contract call attacks in this OEP (nor in OEP4 and OEP8). I think that `transfer` by default should block calls from other smart contracts. There should be a separate method `approveContract` for wallets to whitelist specific contracts for specific tokens. This would prevent malicious contracts from stealing OEP5 assets, as well as enable using OEP5 assets in DEXs (and other non-malicious contracts). I would also be open to turning this last point into a separate OEP for digital asset transfers in general. I think that having this be a foundational standard will protect OEP assets.

Points 1&2 are being addressed by PR #51 
Point 3 is being addressed by PR #48

**Comment by WyattMufson** [comment]
@panther142 agreed with me on point 1. Also agreed on point 2 (and that it applies to OEP8). Making a separate OEP proposal for point 3 (as it applies to all digit assets on Ontology).

**Comment by panther142** [comment]
As @WyattMufson has indicated above, I agree with his assessments.

**Comment by tanZiWen** [comment]
great, we will think about `takeOwnership ` and `transfer` merge proposal

**Comment by tanZiWen** [comment]
we approve you proposal to merge about `takeOwnership` and` transfer`, can you have a PR about it.

**Comment by tanZiWen** [comment]
@WyattMufson

**Comment by tanZiWen** [comment]
i think we also need add `Allowance` to search `approve` owner on OEP-5. @WyattMufson 
`ApprovalForAll(address to, bool approved)` is also need to be added, it has a proposal on Ethereum about it, https://eips.ethereum.org/EIPS/eip-721

**Comment by tanZiWen** [comment]
@panther142

**Comment by WyattMufson** [comment]
@tanZiWen there's a PR open already for points 1 and 2 (#51) and a PR for point 3 (#48)

I can add `allowance` and `approvalForAll`

**Comment by WyattMufson** [comment]
Updated the PR
